# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy package files and install dependencies
COPY package.json package-lock.json ./
RUN npm install 

# Copy rest of the source code
COPY . .

# Build the project
RUN npm run build

# Expose any necessary port (if applicable) - note: MCP typically communicates via stdio, so port exposure may not be needed

# Start the MCP server
CMD ["node", "build/index.js"]
